services:
  neo4j:
    image: neo4j:5-community
    container_name: neo4j-ecommerce
    ports:
      - "7474:7474"   # Neo4j Browser
      - "7687:7687"   # Bolt protocol for drivers
    environment:
      NEO4J_AUTH: "neo4j/password"
      NEO4J_PLUGINS: '["apoc"]'
    volumes:
      - ./neo4j_data:/data
      - ./import:/var/lib/neo4j/import
  
  app: 
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: ecommerce-streamlit
    ports:
      - "8501:8501"   # Streamlit app
    depends_on:
      - neo4j
    environment:
      NEO4J_URI: "bolt://neo4j:7687"
      NEO4J_USER: "neo4j"
      NEO4J_PASSWORD: "password"
    volumes:
      - ./images:/app/images:ro
